plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.parakett.channels'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.2'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.compilerArgs += "-parameters"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            // only keep if artifact name differs
            artifactId = 'channels-base'
        }
    }
}